on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  fedora-rpm-build:
    runs-on: ubuntu-latest
    container: fedora:34
    steps:
      - uses: actions/checkout@v2
      - name: install tools and dependencies
        run: |
          dnf install -y rpm-build findutils clang-tools-extra 'dnf-command(builddep)'
          dnf builddep -y mouse_m908.spec
      - name: build mouse_m908 rpm package
        run: |
          make -j4 rpm
  centos-rpm-build:
    runs-on: ubuntu-latest
    container: centos:8
    steps:
      - uses: actions/checkout@v2
      - name: install tools and dependencies
        run: |
          dnf install -y rpm-build findutils clang-tools-extra 'dnf-command(builddep)' 'dnf-command(config-manager)'
          dnf config-manager --set-enabled powertools
          dnf builddep -y mouse_m908.spec
      - name: build mouse_m908 rpm package
        run: |
          make -j4 rpm
